### ISSUE TITLE
Create a gitignore file to avoid tracking of unwanted local changes 

### ISSUE THREAD

**Issue by MuskanPaliwal** [MuskanPaliwal/Cycling-App#4]

**Comment by N-Harsha** [comment]
i am a newbie and i want to work on this issue could you point me in the right direction

**Comment by MuskanPaliwal** [comment]
Hi @N-Harsha . Actually, this is our course project , I am really sorry but I am not sure whether I can take contribution from someone outside the college. You might start with some other public repository. 
To give your open source journey a kick start, I can help you. 
Thanks :)

**Comment by MuskanPaliwal** [comment]
Hi @N-Harsha . Actually, this is our course project , I am really sorry but I am not sure whether I can take contribution from someone outside the college. You might start with some other public repository.
To give your open source journey a kick start, I can help you.
Thanks :)

**Comment by N-Harsha** [comment]
Sorry i didn't know about that. @MuskanPaliwal thanks for your support : )
